---
    deployment:
      tasks:
        - export DEPLOYPATH=/home/rodseqac/repositories/RodSec/
        - /home/rodseqac/repositories index.html $DEPLOYPATH
          #- /bin/cp style.html $DEPLOYPATH
